# Builder stage
FROM python:3.11-slim-trixie AS builder


# System dependencies
RUN apt-get update \
 && apt-get install --no-install-recommends -y curl build-essential \
 && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
 && apt-get clean -y && rm -rf /var/lib/apt/lists/*

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY . /code

# Final stage
FROM python:3.11-slim-trixie AS production
# test
WORKDIR /code

COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY --from=builder /code /code

EXPOSE 80
ENV FORWARDED_ALLOW_IPS=*
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--workers", "2", "--forwarded-allow-ips", "*", "--proxy-headers"]
